apex/apex/apps/externalfeed/urls.py
from django.conf.urls import url

from apex.apps.externalfeed.views import Index, List, Entry

urlpatterns = [
    url(r'^$', Index.as_view(), name='externalfeed-index'),
    url(r'^list/$', List.as_view(), name='externalfeed-list'),
    url(r'^(?P<path>.*)$', Entry.as_view(), name='externalfeed-entry'),
    ]

apex/apex/apps/services/urls.py
from django.urls import path


from apex.apps.services import views
from django.conf.urls import include, url

app_name = 'services'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    #path(' ', views.index,name='index'),
    path('archive/', views.archive, name='archive'),
    path('<int:year>/',views.year, name='year'),
    path('<int:year>/<int:month>',views.month, name='month'),
    path('<int:year>/<int:month>/<int:day>/',views.day,name='day'),
]

apex/apex/urls.py
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import include, path
from apex.apps.core import views as core_views
from apex.apps.services import views as services_views
from apex.templates.services.includes import views as B_view

from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apex.apps.services.models import BookmarkArticle
from apex.apps.services.views  import successView, feedbackView, aboutView, searchView, searchResultView

urlpatterns = [
    path('', services_views.front_page, name='front_page'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('signup/', services_views.register_user, name='signup'),
    path('feedback/', services_views.feedbackView, name='feedback'),
    path('success/', successView, name='success'),
    path('about/', aboutView, name='about'),
    path('search/',searchView,name='search'),
    path('about/', TemplateView.as_view(template_name='core/about.html'), name='about'),
    path('status/', core_views.status, name='status'),
    path('cookies/', TemplateView.as_view(template_name='core/cookies.html'), name='cookies'),
    path('privacy/', TemplateView.as_view(template_name='core/privacy.html'), name='privacy'),
    path('FAQ/', TemplateView.as_view(template_name='core/FAQ.html'), name='FAQ'),
    path('terms/', TemplateView.as_view(template_name='core/terms.html'), name='terms'),
    path('bookmarks/',B_view.BookmarksView.as_view(),name='bookmarks'),
    path('<slug:slug>/', include('apex.apps.services.urls', namespace='services')),
    path('<pk>/bookmark/',services_views.BookmarkView.as_view(model=BookmarkArticle),
        name='article_bookmark'),
    path('externalnews/', include('apex.apps.externalfeed.urls')),

    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    try:
        import debug_toolbar
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
    except ImportError:
        print()
        pass

apex/apex/apps/accounts/models.py
from django.db import models

apex/apex/apps/services/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user




class FeedbackForm(forms.Form):
    name = forms.CharField(max_length=200)
    email = forms.EmailField(required=True)
    subject = forms.CharField(max_length=200)
    message = forms.CharField(max_length=2000,widget=forms.Textarea(),help_text='Write here your message!')

apex/apex/apps/core/views.py
from django.shortcuts import render

from apex.apps.services.models import Service 

def status(request):
    services = Service.objects.all()
    return render(request,'core/status.html',{
        'services':services
    })

apex/apex/apps/externalfeed/views.py
from django.views.generic.base import TemplateView


class Index(TemplateView):
    """Index of feed items.
    """
    template_name = 'externalfeed/index.html'


class List(Index):
    """Simple list of feed items.

    Just an ul/li list.
    """
    template_name = 'externalfeed/list.html'


class Entry(TemplateView):
    """Display a feed entry.
    """
    template_name = 'externalfeed/entry.html'

    def get_context_data(self, **kwargs):
        data = super(Entry, self).get_context_data(**kwargs)
        path = kwargs['path']
        if '/' in path:
            # Split the path into a key (to know which feed source to
            # query) and the rest of the path.
            key, path = path.split('/', 1)
            data['key'] = key
            data['path'] = path
        return data

apex/apex/apps/services/views.py
import datetime
import json
from collections import OrderedDict
from itertools import groupby

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Sum, Min
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, render_to_response
from django.template.context_processors import csrf
from django.utils import timezone
from django.views.decorators.cache import cache_page

from apex.apps.services.forms import RegistrationForm
from apex.apps.services.models import Service, Story, BookmarkArticle,FeedbackModel
from apex.apps.services.utils import remove_duplicates

import json

from django.contrib import auth
from django.http import HttpResponse
from django.views import View

from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import FeedbackForm
from django.shortcuts import render
from django.db.models import Q
from .models import PostModel



def stories(request, service, queryset, subtitle):
    paginator = Paginator(queryset, 20)
    page = request.GET.get('page')
    try:
        stories = paginator.page(page)
    except PageNotAnInteger:
        stories = paginator.page(1)
    except EmptyPage:
        stories = paginator.page(paginator.num_pages)

    if stories.number > 1:
        start = (stories.number - 1) * 20 + 1
    else:
        start = 1

    if 'application/json' in request.META.get('HTTP_ACCEPT'):
        stories_dict = map(lambda story: story.to_dict(), stories)
        dump = json.dumps({
            'service': service.to_dict(),
            'stories': stories_dict,
            'subtitle': subtitle
        })
        return HttpResponse(dump, content_type='application/json')
    else:
        return render(request, 'services/stories.html', {
            'service': service,
            'stories': stories,
            'subtitle': subtitle,
            'start': start
        })


@cache_page(60)
def front_page(request):
    today = timezone.now()
    stories = list()
    services = Service.objects.all()
    for service in services:
        top_story = service.stories.filter(status=Story.OK, date=today).order_by('-score').first()
        if top_story:
            stories.append(top_story)
    subtitle = today.strftime('%d %b %Y')

    if 'application/json' in request.META.get('HTTP_ACCEPT'):
        stories_dict = map(lambda story: story.to_dict(), stories)
        dump = json.dumps({
            'stories': stories_dict,
            'subtitle': subtitle
        })
        return HttpResponse(dump, content_type='application/json')
    else:
        return render(request, 'services/front_page.html', {'stories': stories, 'subtitle': subtitle})


@cache_page(60)
def index(request, slug):
    today = timezone.now()
    return day(request, slug, today.year, today.month, today.day)


@cache_page(5 * 60)
def year(request, slug, year):
    service = get_object_or_404(Service, slug=slug)
    queryset = service.stories \
        .filter(status=Story.OK, date__year=year) \
        .values('url', 'title') \
        .annotate(score=Sum('score'), date=Min('date')) \
        .order_by('-score')
    return stories(request, service, queryset, year)


@cache_page(5 * 60)
def month(request, slug, year, month):
    service = get_object_or_404(Service, slug=slug)
    queryset = service.stories \
        .filter(status=Story.OK, date__year=year, date__month=month) \
        .values('url', 'title') \
        .annotate(score=Sum('score'), date=Min('date')) \
        .order_by('-score')
    subtitle = timezone.datetime(int(year), int(month), 1).strftime('%b %Y')
    return stories(request, service, queryset, subtitle)


@cache_page(5 * 60)
def day(request, slug, year, month, day):
    date = datetime.datetime(int(year), int(month), int(day))
    service = get_object_or_404(Service, slug=slug)
    queryset = service.stories.filter(status=Story.OK, date=date)[:100]
    subtitle = timezone.datetime(int(year), int(month), int(day)).strftime('%d %b %Y')
    return stories(request, service, queryset, subtitle)


@cache_page(60 * 60)
def archive(request, slug):
    service = get_object_or_404(Service, slug=slug)

    dates = service.stories.all().order_by('-date').values_list('date', flat=True)
    str_dates = map(lambda date: date.strftime('%Y-%m-%d'), dates)
    str_dates = remove_duplicates(str_dates)

    archive = OrderedDict()
    for year, months in groupby(str_dates, lambda date: date[:4]):
        archive[year] = OrderedDict()
        for month, days in groupby(months, lambda date: date[5:7]):
            archive[year][month] = list()
            for day in days:
                archive[year][month].append(day[8:10])

    if 'application/json' in request.META.get('HTTP_ACCEPT'):
        dump = json.dumps(archive)
        return HttpResponse(dump, content_type='application/json')
    else:
        return render(request, 'services/archive.html', {
            'service': service,
            'archive': archive
        })


def register_user(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')

    args = {}
    args.update(csrf(request))

    args['form'] = RegistrationForm()

    return render_to_response('registration/signup.html', args)

class BookmarkView(View):
    # This variable will set the bookmark model to be processed
    model = None

    def post(self, request, pk):
        # We need a user
        user = auth.get_user(request)
        # Trying to get a bookmark from the table, or create a new one
        bookmark, created = self.model.objects.get_or_create(user=user, obj_id=pk)
        # If no new bookmark has been created,
        # Then we believe that the request was to delete the bookmark
        if not created:
            bookmark.delete()

        return HttpResponse(
            json.dumps({
                "result": created,
                "count": self.model.objects.filter(obj_id=pk).count()
            }),
            content_type="application/json"
        )


def feedbackView(request):
    if request.method == 'GET':
        form  = FeedbackForm()
    else:
        form = FeedbackForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            feedbackmodel = FeedbackModel.objects.create(name=name,email=email,subject=subject,message=message)
            try:
                send_mail(message,subject,email,['tikamalma1@gmail.com'])
            except BadHeaderError:
                return  HttpResponse('Invalid Header Found')
            return redirect('success')
    return render(request,'feedback.html',{'form':form})


def successView(request):
    return HttpResponse(render(request,'success.html'))


def aboutView(request):
    return render(request,'about_us.html')

def queryLookup(query):
    lookups= Q(title__icontains=query) | Q(content__icontains=query)
    return Story.objects.filter(lookups).distinct()


def searchView(request):
   # return render(request,'search_posts.html')
    if request.method == 'GET':
        query= request.GET.get('q')

        if query:
            results = queryLookup(query)
            return render(request,'services/search_result.html', {
                'results': results
            })

        else:
            return render(request,'services/search_result.html')

    else:
        return render(request,'services/search_result.html')


def searchResultView(request):
    return render(request,'search_result.html')

apex/apex/templates/services/includes/views.py
from django.shortcuts import render

from apex.apps.services.models import BookmarkArticle

from django.contrib.auth.models import User

from apex.apps.services.models import BookmarkArticle,Service

from django.views import View

from django.contrib import auth

class BookmarksView(View):
	
	model = None

	def get(self,request):
		bookmarks = BookmarkArticle.objects.all()
		user = auth.get_user(request)
		service = Service.objects.all()
		context = {'user': user, 'bookmarks': bookmarks,'services': service}
		return render(request,"bookmarks.html",context)

apex/apex/templates/services/includes/Business-Insider_story.html
<br></br>
<li>
  <a href="{{ story.url }}" target="_blank" rel="nofollow noopener">{{ story.title }}</a>
  {% if story.nsfw %}
    <small class="nsfw">[nsfw]</small>
  {% endif %}
  <!--	<button type="bullet" value="reset">Bookmark this</button> -->
  <p>
  	{{ story.description }}
  </p>
  <p>
    &bullet;
    {{ story.date|date:'M d, Y'|lower }}
  </p>
  {% include 'services/includes/bookmark_sec.html' %}

</li>

apex/apex/templates/services/includes/bbc-sport_story.html
<br></br>
<li>
  <div id="posttitle">
  <a href="{{ story.url }}" target="_blank" rel="nofollow noopener" id="ptitle">{{ story.title }}</a>
  {% if story.nsfw %}
    <small class="nsfw">[nsfw]</small>
  {% endif %}
</div>
<div class="postcontent">
  <p style=" text-transform: capitalize;">
    {{ story.date|date:'M d, Y'|lower }}
    <div id="bookmark_post">
      <span style="float: right;font-size: 20px; margin: 15px; margin-left: 0px; margin-bottom: 0px;">
          <span class="fb-share-button"
         data-href="{{ story.url }}"
         data-layout="button_count" data-size="small">
      <a target="_blank"
         href="https://www.facebook.com/sharer/sharer.php?u={{ story.url }}"
         class="fb-xfbml-parse-ignore"> <i class="fa fa-facebook"></i></a>
    </span>
          <a class="twitter-share-button"
       href="https://twitter.com/intent/tweet?text={{ story.url }}"
       data-size="large"> <i class="fa fa-twitter"></i></a>
          <a class="linkedin-share-button"
       href="https://www.linkedin.com/shareArticle?mini=true&url={{ story.url }}&title={{ story.title }}
  "
       data-size="large"><i class="fa fa-linkedin"></i></a>
  </span>
  {% include 'services/includes/bookmark_sec.html' %}
</div>
</p>
<table>
    <th class="story">
  <img src= {{ story.image_url }} alt="We could not display the image" height=150></th>
    <th class="story">
  <p style="font-size:17px">
    {{ story.description }}
  </p>
</th>
</table>
  </div> 
</li>

apex/apex/templates/services/includes/bookmark_sec.html
{% load services_url %}
{% if user.is_authenticated %}
<span data-id="{{ story.id }}" data-type="article" data-action="bookmark" title="Favorites" style="float: right;font-size: 20px; margin: 15px;">
    <button type="button" class="btn btn-link">
      {% if story.bookmarkarticle_set.all|user_in:user %}
      <span class="star glyphicon glyphicon-star"></span></button>
      {% else %}
      <span class="star glyphicon glyphicon-star-empty"></span></button>
      {% endif %}
</span>
{% endif %}

apex/apex/templates/services/includes/entertainment-weekly_story.html
<br></br>
<li>
  <div id="posttitle">
  <a href="{{ story.url }}" target="_blank" rel="nofollow noopener" id="ptitle">{{ story.title }}</a>
  {% if story.nsfw %}
    <small class="nsfw">[nsfw]</small>
  {% endif %}
</div>
<div class="postcontent">
  <p style=" text-transform: capitalize;">
    {{ story.date|date:'M d, Y'|lower }}
    <div id="bookmark_post">
      <span style="float: right;font-size: 20px; margin: 15px; margin-left: 0px; margin-bottom: 0px;">
          <span class="fb-share-button"
         data-href="{{ story.url }}"
         data-layout="button_count" data-size="small">
      <a target="_blank"
         href="https://www.facebook.com/sharer/sharer.php?u={{ story.url }}"
         class="fb-xfbml-parse-ignore"> <i class="fa fa-facebook"></i></a>
    </span>
          <a class="twitter-share-button"
       href="https://twitter.com/intent/tweet?text={{ story.url }}"
       data-size="large"> <i class="fa fa-twitter"></i></a>
          <a class="linkedin-share-button"
       href="https://www.linkedin.com/shareArticle?mini=true&url={{ story.url }}&title={{ story.title }}
  "
       data-size="large"><i class="fa fa-linkedin"></i></a>
  </span>
  {% include 'services/includes/bookmark_sec.html' %}
</div>
</p>
<table>
    <th class="story">
  <img src= {{ story.image_url }} alt="We could not display the image" height=150></th>
    <th class="story">
  <p style="font-size:17px">
    {{ story.description }}
  </p>
</th>
</table>
  </div> 
</li>

apex/apex/templates/services/includes/google-news_story.html
<br></br>
<li>
  <div id="posttitle">
  <a href="{{ story.url }}" target="_blank" rel="nofollow noopener" id="ptitle">{{ story.title }}</a>
  {% if story.nsfw %}
    <small class="nsfw">[nsfw]</small>
  {% endif %}
</div>
<div class="postcontent">
  <p style=" text-transform: capitalize;">
    {{ story.date|date:'M d, Y'|lower }}
    <div id="bookmark_post">
      <span style="float: right;font-size: 20px; margin: 15px; margin-left: 0px; margin-bottom: 0px;">
          <span class="fb-share-button"
         data-href="{{ story.url }}"
         data-layout="button_count" data-size="small">
      <a target="_blank"
         href="https://www.facebook.com/sharer/sharer.php?u={{ story.url }}"
         class="fb-xfbml-parse-ignore"> <i class="fa fa-facebook"></i></a>
    </span>
          <a class="twitter-share-button"
       href="https://twitter.com/intent/tweet?text={{ story.url }}"
       data-size="large"> <i class="fa fa-twitter"></i></a>
          <a class="linkedin-share-button"
       href="https://www.linkedin.com/shareArticle?mini=true&url={{ story.url }}&title={{ story.title }}
  "
       data-size="large"><i class="fa fa-linkedin"></i></a>
  </span>
  {% include 'services/includes/bookmark_sec.html' %}
</div>
</p>
<table>
    <th class="story">
  <img src= {{ story.image_url }} alt="We could not display the image" height=150></th>
    <th class="story">
  <p style="font-size:17px">
    {{ story.description }}
  </p>
</th>
</table>
  </div> 
</li>

apex/apex/templates/services/includes/hn_story.html
<li>
  <div id="posttitle" >
  <a href="{{ story.url }}" target="_blank" rel="nofollow noopener" id="ptitle">{{ story.title }}</a>
</div>
<div id="reddit_post"> 
  <p >
    <div id="left" style=" text-transform: capitalize;">
    {{ story.score }} upvote{{ story.score|pluralize }}
    &bullet;
    {{ story.comments }} comment{{ story.comments|pluralize }}
    &bullet;
    {{ story.date|date:'M d, Y'|lower }}
  </div>
    <div id="bookmark_hn">
      <span style="float: right;font-size: 20px; margin: 15px; margin-left: 0px; margin-bottom: 0px;">
          <span class="fb-share-button"
         data-href="{{ story.url }}"
         data-layout="button_count" data-size="small">
      <a target="_blank"
         href="https://www.facebook.com/sharer/sharer.php?u={{ story.url }}"
         class="fb-xfbml-parse-ignore"> <i class="fa fa-facebook"></i></a>
    </span>
          <a class="twitter-share-button"
       href="https://twitter.com/intent/tweet?text={{ story.url }}"
       data-size="large"> <i class="fa fa-twitter"></i></a>
          <a class="linkedin-share-button"
       href="https://www.linkedin.com/shareArticle?mini=true&url={{ story.url }}&title={{ story.title }}
  "
       data-size="large"><i class="fa fa-linkedin"></i></a>
  </span>
      {% include 'services/includes/bookmark_sec.html' %}
    </div>
  </p>
</div>
</li>

apex/apex/templates/services/includes/medium_story.html
<li>
  <a href="{{ story.url }}" target="_blank" rel="nofollow noopener">{{ story.title }}</a>
  <p>
    {{ story.score }} recommend{{ story.score|pluralize }}
    &bullet;
    {{ story.comments }} comment{{ story.comments|pluralize }}
    &bullet;
    {{ story.date|date:'M d, Y'|lower }}
  </p>
</li>

apex/apex/templates/services/includes/menu.html
{% load services_url %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}Online Trending{% endblock %}</title>
<link href="{% static 'css/woid.css' %}" rel="stylesheet" >
{% block stylesheet %}{% endblock %}
</head>
<ul class="menu-stories" >
  <li><a href="{% url 'services:index' service.slug %}" class="button" style="
  text-transform: capitalize;"><span>today</span></a></li>
  <li><a href="{% services_url slug=service.slug delta=1 %}" class="button" style="
  text-transform: capitalize;"><span>yesterday</span></a></li>
  <li><a href="{% services_url slug=service.slug delta=2 %}" class="button" style="
  text-transform: capitalize;"><span>{% services_url_name slug=service.slug delta=2 %}</span></a></li>
  <li><a href="{% services_url slug=service.slug delta=3 %}" class="button" style="
  text-transform: capitalize;"><span>{% services_url_name slug=service.slug delta=3 %}</span></a></li>
  <li><a href="{% services_url slug=service.slug delta=4 %}" class="button" style="
  text-transform: capitalize;"><span>{% services_url_name slug=service.slug delta=4 %}</span></a></li>
  <li><a href="{% services_url slug=service.slug delta=5 %}" class="button" style="
  text-transform: capitalize;"><span>{% services_url_name slug=service.slug delta=5 %}</span></a></li>
  <li><a href="{% services_url slug=service.slug delta=6 %}" class="button" style="
  text-transform: capitalize;"><span>{% services_url_name slug=service.slug delta=6 %}</span></a></li>
  <li><a href="{% services_url_month slug=service.slug %}" class="button" style="
  text-transform: capitalize;"><span>{% services_url_month_name %}</span></a></li>
  <li><a href="{% services_url_year slug=service.slug %}" class="button" style="
  text-transform: capitalize;"><span>{% now 'Y' %}</span></a></li>
  <li><a href="{% url 'services:archive' service.slug %}" class="button" style="
  text-transform: capitalize;"><span>archive</span></a></li>
</ul>
</html>

apex/apex/templates/services/includes/nytimes_story.html
<li>
  <div id="posttitle">
  <a href="{{ story.url }}" target="_blank" rel="nofollow noopener" id="ptitle">{{ story.title }}</a>
</div>
<div class="postcontent">
  <p style=" text-transform: capitalize;">
    {{ story.score }} point{{ story.score|pluralize }}
    {{ story.date|date:'M d, Y'|lower }}
    <div id="bookmark_post">
      <span style="float: right;font-size: 20px; margin: 15px; margin-left: 0px; margin-bottom: 0px;">
          <span class="fb-share-button"
         data-href="{{ story.url }}"
         data-layout="button_count" data-size="small">
      <a target="_blank"
         href="https://www.facebook.com/sharer/sharer.php?u={{ story.url }}"
         class="fb-xfbml-parse-ignore"> <i class="fa fa-facebook"></i></a>
    </span>
          <a class="twitter-share-button"
       href="https://twitter.com/intent/tweet?text={{ story.url }}"
       data-size="large"> <i class="fa fa-twitter"></i></a>
          <a class="linkedin-share-button"
       href="https://www.linkedin.com/shareArticle?mini=true&url={{ story.url }}&title={{ story.title }}
  "
       data-size="large"><i class="fa fa-linkedin"></i></a>
  </span>
  {% include 'services/includes/bookmark_sec.html' %}
</div>
  </p>
  <table>
    <th class="story">
  <img src= {{ story.image_url }} alt="We could not display the image" height=150></th>
    <th class="story">
  <p style="font-size:17px">
    {{ story.description }}
  </p>
</th>
</table>
</div>
</li>

apex/apex/templates/services/includes/reddit_story.html
<li>
  <div id="posttitle">
  <a href="{{ story.url }}" target="_blank" rel="nofollow noopener" id="ptitle">{{ story.title }}</a>
  {% if story.nsfw %}
    <small class="nsfw">[nsfw]</small>
  {% endif %}
</div>
<div id="reddit_post"> 
  <p >
    <div id="left" style=" text-transform: capitalize;">
    {{ story.score }} upvote{{ story.score|pluralize }}
    &bullet;
    {{ story.comments }} comment{{ story.comments|pluralize }}
    &bullet;
    {{ story.date|date:'M d, Y'|lower }}
  </div>
    <div id="bookmark_hn" style="padding: 0px 5px;">
  <span style="float: right;font-size: 20px; margin: 15px; margin-left: 0px; margin-bottom: 0px;">
          <span class="fb-share-button"
         data-href="{{ story.url }}"
         data-layout="button_count" data-size="small">
      <a target="_blank"
         href="https://www.facebook.com/sharer/sharer.php?u={{ story.url }}"
         class="fb-xfbml-parse-ignore"> <i class="fa fa-facebook"></i></a>
    </span>
          <a class="twitter-share-button"
       href="https://twitter.com/intent/tweet?text={{ story.url }}"
       data-size="large"> <i class="fa fa-twitter"></i></a>
          <a class="linkedin-share-button"
       href="https://www.linkedin.com/shareArticle?mini=true&url={{ story.url }}&title={{ story.title }}
  "
       data-size="large"><i class="fa fa-linkedin"></i></a>
  </span>
      {% include 'services/includes/bookmark_sec.html' %}
    </div>
  </p>
</div>
</li>

apex/apex/templates/services/includes/rss-feed_story.html
<li>
  <div id="posttitle">
  <a href="{{ story.url }}" target="_blank" rel="nofollow noopener" id="ptitle">{{ story.title }}</a>
  <!--  <button type="bullet" value="reset">Bookmark this</button> -->
  </div>
<div class="postcontent">
  <p style=" text-transform: capitalize;">
    {{ story.date|date:'M d, Y'|lower }}
    <div id="bookmark_post">
      <span style="float: right;font-size: 20px; margin: 15px; margin-left: 0px; margin-bottom: 0px;">
          <span class="fb-share-button"
         data-href="{{ story.url }}"
         data-layout="button_count" data-size="small">
      <a target="_blank"
         href="https://www.facebook.com/sharer/sharer.php?u={{ story.url }}"
         class="fb-xfbml-parse-ignore"> <i class="fa fa-facebook"></i></a>
    </span>
          <a class="twitter-share-button"
       href="https://twitter.com/intent/tweet?text={{ story.url }}"
       data-size="large"> <i class="fa fa-twitter"></i></a>
          <a class="linkedin-share-button"
       href="https://www.linkedin.com/shareArticle?mini=true&url={{ story.url }}&title={{ story.title }}
  "
       data-size="large"><i class="fa fa-linkedin"></i></a>
  </span>
  {% include 'services/includes/bookmark_sec.html' %}
</div>
  </p>
  <p style="font-size:17px; font-weight: bold;">
    {{ story.description }}
  </p>
</div>
</li>